#ifndef LIBXBMCREMOTE_GLOBAL_H
#define LIBXBMCREMOTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBXBMCREMOTE_LIBRARY)
#  define LIBXBMCREMOTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBXBMCREMOTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBXBMCREMOTE_GLOBAL_H
